//**************************************************************************
//
//  Open Robot I/O
//
//    Copyright (C) 2019 John Winans
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
//**************************************************************************

#include "orio_dio.h"

#include "board.h"
#include "peripherals.h"
#include "pin_mux.h"
#include "LPC54606.h"

#include "fsl_gpio.h"


void setSOL(uint16_t i)
{
	GPIO_PinWrite(BOARD_INITPINS_SOL_0_GPIO, BOARD_INITPINS_SOL_0_PORT, BOARD_INITPINS_SOL_0_PIN, (i&0x001)!=0);
	GPIO_PinWrite(BOARD_INITPINS_SOL_1_GPIO, BOARD_INITPINS_SOL_1_PORT, BOARD_INITPINS_SOL_1_PIN, (i&0x002)!=0);
	GPIO_PinWrite(BOARD_INITPINS_SOL_2_GPIO, BOARD_INITPINS_SOL_2_PORT, BOARD_INITPINS_SOL_2_PIN, (i&0x004)!=0);
	GPIO_PinWrite(BOARD_INITPINS_SOL_3_GPIO, BOARD_INITPINS_SOL_3_PORT, BOARD_INITPINS_SOL_3_PIN, (i&0x008)!=0);
	GPIO_PinWrite(BOARD_INITPINS_SOL_4_GPIO, BOARD_INITPINS_SOL_4_PORT, BOARD_INITPINS_SOL_4_PIN, (i&0x010)!=0);
	GPIO_PinWrite(BOARD_INITPINS_SOL_5_GPIO, BOARD_INITPINS_SOL_5_PORT, BOARD_INITPINS_SOL_5_PIN, (i&0x020)!=0);
	GPIO_PinWrite(BOARD_INITPINS_SOL_6_GPIO, BOARD_INITPINS_SOL_6_PORT, BOARD_INITPINS_SOL_6_PIN, (i&0x040)!=0);
	GPIO_PinWrite(BOARD_INITPINS_SOL_7_GPIO, BOARD_INITPINS_SOL_7_PORT, BOARD_INITPINS_SOL_7_PIN, (i&0x080)!=0);
}
void setRLY(uint16_t i)
{
	GPIO_PinWrite(BOARD_INITPINS_RLY_0_GPIO, BOARD_INITPINS_RLY_0_PORT, BOARD_INITPINS_RLY_0_PIN, (i&0x001)!=0);
	GPIO_PinWrite(BOARD_INITPINS_RLY_1_GPIO, BOARD_INITPINS_RLY_1_PORT, BOARD_INITPINS_RLY_1_PIN, (i&0x002)!=0);
	GPIO_PinWrite(BOARD_INITPINS_RLY_2_GPIO, BOARD_INITPINS_RLY_2_PORT, BOARD_INITPINS_RLY_2_PIN, (i&0x004)!=0);
	GPIO_PinWrite(BOARD_INITPINS_RLY_3_GPIO, BOARD_INITPINS_RLY_3_PORT, BOARD_INITPINS_RLY_3_PIN, (i&0x008)!=0);
	GPIO_PinWrite(BOARD_INITPINS_RLY_4_GPIO, BOARD_INITPINS_RLY_4_PORT, BOARD_INITPINS_RLY_4_PIN, (i&0x010)!=0);
	GPIO_PinWrite(BOARD_INITPINS_RLY_5_GPIO, BOARD_INITPINS_RLY_5_PORT, BOARD_INITPINS_RLY_5_PIN, (i&0x020)!=0);
	GPIO_PinWrite(BOARD_INITPINS_RLY_6_GPIO, BOARD_INITPINS_RLY_6_PORT, BOARD_INITPINS_RLY_6_PIN, (i&0x040)!=0);
	GPIO_PinWrite(BOARD_INITPINS_RLY_7_GPIO, BOARD_INITPINS_RLY_7_PORT, BOARD_INITPINS_RLY_7_PIN, (i&0x080)!=0);
}

void setLED(uint16_t i)
{
	GPIO_PinWrite(BOARD_INITPINS_LED_1_GPIO, BOARD_INITPINS_LED_1_PORT, BOARD_INITPINS_LED_1_PIN, (i&0x001)!=0);
	GPIO_PinWrite(BOARD_INITPINS_LED_2_GPIO, BOARD_INITPINS_LED_2_PORT, BOARD_INITPINS_LED_2_PIN, (i&0x002)!=0);
	GPIO_PinWrite(BOARD_INITPINS_LED_3_GPIO, BOARD_INITPINS_LED_3_PORT, BOARD_INITPINS_LED_3_PIN, (i&0x004)!=0);
	GPIO_PinWrite(BOARD_INITPINS_LED_4_GPIO, BOARD_INITPINS_LED_4_PORT, BOARD_INITPINS_LED_4_PIN, (i&0x008)!=0);
	GPIO_PinWrite(BOARD_INITPINS_LED_5_GPIO, BOARD_INITPINS_LED_5_PORT, BOARD_INITPINS_LED_5_PIN, (i&0x010)!=0);
	GPIO_PinWrite(BOARD_INITPINS_LED_6_GPIO, BOARD_INITPINS_LED_6_PORT, BOARD_INITPINS_LED_6_PIN, (i&0x020)!=0);
	GPIO_PinWrite(BOARD_INITPINS_LED_7_GPIO, BOARD_INITPINS_LED_7_PORT, BOARD_INITPINS_LED_7_PIN, (i&0x040)!=0);
	GPIO_PinWrite(BOARD_INITPINS_LED_8_GPIO, BOARD_INITPINS_LED_8_PORT, BOARD_INITPINS_LED_8_PIN, (i&0x080)!=0);
	GPIO_PinWrite(BOARD_INITPINS_LED_9_GPIO, BOARD_INITPINS_LED_9_PORT, BOARD_INITPINS_LED_9_PIN, (i&0x100)!=0);
}

void setDIO(uint16_t i)
{
	GPIO_PinWrite(BOARD_INITPINS_DIO_0_GPIO, BOARD_INITPINS_DIO_0_PORT, BOARD_INITPINS_DIO_0_PIN, (i&0x001)!=0);
	GPIO_PinWrite(BOARD_INITPINS_DIO_1_GPIO, BOARD_INITPINS_DIO_1_PORT, BOARD_INITPINS_DIO_1_PIN, (i&0x002)!=0);
	GPIO_PinWrite(BOARD_INITPINS_DIO_2_GPIO, BOARD_INITPINS_DIO_2_PORT, BOARD_INITPINS_DIO_2_PIN, (i&0x004)!=0);
	GPIO_PinWrite(BOARD_INITPINS_DIO_3_GPIO, BOARD_INITPINS_DIO_3_PORT, BOARD_INITPINS_DIO_3_PIN, (i&0x008)!=0);
	GPIO_PinWrite(BOARD_INITPINS_DIO_4_GPIO, BOARD_INITPINS_DIO_4_PORT, BOARD_INITPINS_DIO_4_PIN, (i&0x010)!=0);
	GPIO_PinWrite(BOARD_INITPINS_DIO_5_GPIO, BOARD_INITPINS_DIO_5_PORT, BOARD_INITPINS_DIO_5_PIN, (i&0x020)!=0);
	GPIO_PinWrite(BOARD_INITPINS_DIO_6_GPIO, BOARD_INITPINS_DIO_6_PORT, BOARD_INITPINS_DIO_6_PIN, (i&0x040)!=0);
	GPIO_PinWrite(BOARD_INITPINS_DIO_7_GPIO, BOARD_INITPINS_DIO_7_PORT, BOARD_INITPINS_DIO_7_PIN, (i&0x080)!=0);
	GPIO_PinWrite(BOARD_INITPINS_DIO_8_GPIO, BOARD_INITPINS_DIO_8_PORT, BOARD_INITPINS_DIO_8_PIN, (i&0x100)!=0);
	GPIO_PinWrite(BOARD_INITPINS_DIO_9_GPIO, BOARD_INITPINS_DIO_9_PORT, BOARD_INITPINS_DIO_9_PIN, (i&0x200)!=0);
}


uint16_t getDIO()
{
	uint16_t i;
	i  = GPIO_PinRead(BOARD_INITPINS_DIO_0_GPIO, BOARD_INITPINS_DIO_0_PORT, BOARD_INITPINS_DIO_0_PIN) ? 1<<0 : 0;
	i |= GPIO_PinRead(BOARD_INITPINS_DIO_1_GPIO, BOARD_INITPINS_DIO_1_PORT, BOARD_INITPINS_DIO_1_PIN) ? 1<<1 : 0;
	i |= GPIO_PinRead(BOARD_INITPINS_DIO_2_GPIO, BOARD_INITPINS_DIO_2_PORT, BOARD_INITPINS_DIO_2_PIN) ? 1<<2 : 0;
	i |= GPIO_PinRead(BOARD_INITPINS_DIO_3_GPIO, BOARD_INITPINS_DIO_3_PORT, BOARD_INITPINS_DIO_3_PIN) ? 1<<3 : 0;
	i |= GPIO_PinRead(BOARD_INITPINS_DIO_4_GPIO, BOARD_INITPINS_DIO_4_PORT, BOARD_INITPINS_DIO_4_PIN) ? 1<<4 : 0;
	i |= GPIO_PinRead(BOARD_INITPINS_DIO_5_GPIO, BOARD_INITPINS_DIO_5_PORT, BOARD_INITPINS_DIO_5_PIN) ? 1<<5 : 0;
	i |= GPIO_PinRead(BOARD_INITPINS_DIO_6_GPIO, BOARD_INITPINS_DIO_6_PORT, BOARD_INITPINS_DIO_6_PIN) ? 1<<6 : 0;
	i |= GPIO_PinRead(BOARD_INITPINS_DIO_7_GPIO, BOARD_INITPINS_DIO_7_PORT, BOARD_INITPINS_DIO_7_PIN) ? 1<<7 : 0;
	i |= GPIO_PinRead(BOARD_INITPINS_DIO_8_GPIO, BOARD_INITPINS_DIO_8_PORT, BOARD_INITPINS_DIO_8_PIN) ? 1<<8 : 0;
	i |= GPIO_PinRead(BOARD_INITPINS_DIO_9_GPIO, BOARD_INITPINS_DIO_9_PORT, BOARD_INITPINS_DIO_9_PIN) ? 1<<9 : 0;
	return i;
}

uint16_t getSwitch()
{
	uint16_t i;
	i  = GPIO_PinRead(BOARD_INITPINS_SW_0_GPIO, BOARD_INITPINS_SW_0_PORT, BOARD_INITPINS_SW_0_PIN) ? 1<<0 : 0;
	i |= GPIO_PinRead(BOARD_INITPINS_SW_1_GPIO, BOARD_INITPINS_SW_1_PORT, BOARD_INITPINS_SW_1_PIN) ? 1<<1 : 0;
	i |= GPIO_PinRead(BOARD_INITPINS_SW_2_GPIO, BOARD_INITPINS_SW_2_PORT, BOARD_INITPINS_SW_2_PIN) ? 1<<2 : 0;
	i |= GPIO_PinRead(BOARD_INITPINS_SW_3_GPIO, BOARD_INITPINS_SW_3_PORT, BOARD_INITPINS_SW_3_PIN) ? 1<<3 : 0;
	i |= GPIO_PinRead(BOARD_INITPINS_SW_4_GPIO, BOARD_INITPINS_SW_4_PORT, BOARD_INITPINS_SW_4_PIN) ? 1<<4 : 0;
	i |= GPIO_PinRead(BOARD_INITPINS_SW_5_GPIO, BOARD_INITPINS_SW_5_PORT, BOARD_INITPINS_SW_5_PIN) ? 1<<5 : 0;
	i |= GPIO_PinRead(BOARD_INITPINS_SW_6_GPIO, BOARD_INITPINS_SW_6_PORT, BOARD_INITPINS_SW_6_PIN) ? 1<<6 : 0;
	i |= GPIO_PinRead(BOARD_INITPINS_SW_7_GPIO, BOARD_INITPINS_SW_7_PORT, BOARD_INITPINS_SW_7_PIN) ? 1<<7 : 0;
	return i;
}

